steps:
  - name: gcr.io/cloud-builders/mvn
    args:
      - '-B'
      - install
      - appengine:stage
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-m'
      - cp
      - '-r'
      - target/appengine-staging
      - gs://genesis-buckets-build/int/gae-skeleton/${execution.startTime}
